Fix beta key download
Problem:
```
$ docker run --rm -it lasley/makemkvcon
Traceback (most recent call last):
  File "/entrypoint.d/20-create-makemkv-settings", line 33, in <module>
    APP_KEY = matches.group('key')
AttributeError: 'NoneType' object has no attribute 'group'
run-parts: /entrypoint.d/20-create-makemkv-settings exited with return code 1
```

The [regex pattern](https://github.com/lasley/docker-makemkvcon/blob/91a0c3b742ac0cb3f75648b59077b39e5f068f83/entrypoint.d/20-create-makemkv-settings#L30) to extract the beta key from the website (`'<div class="codecontent">(?P<key>.+?)</div>'`) does not match, probably the website changed in the past.

jlesage/docker-makemkv uses a [different pattern](https://github.com/jlesage/docker-makemkv/blob/49765065a2e9d7b588c9f99e4ee19f96f31320b3/rootfs/opt/makemkv/bin/makemkv-update-beta-key#L36) (`.*<code>\(.*\)</code>.*`) that works.

The website currently contains:
```
<div class="codebox"><p>Code: <a href="#" onclick="selectCode(this); return false;">Select all</a></p><pre><code>...</code></pre></div> and is valid until end of March 2020. Please check back for updated key on this page.</div>
```

I also noticed that the URL used [here](https://github.com/lasley/docker-makemkvcon/blob/91a0c3b742ac0cb3f75648b59077b39e5f068f83/entrypoint.d/20-create-makemkv-settings#L27) contains `/forum2/` whereas the URL used [in the other project](https://github.com/jlesage/docker-makemkv/blob/49765065a2e9d7b588c9f99e4ee19f96f31320b3/rootfs/opt/makemkv/bin/makemkv-update-beta-key#L29) uses `/forum/`.